# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_interlis.ui'
#
# Created: Thu Mar  5 00:29:51 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Interlis(object):
    def setupUi(self, Interlis):
        Interlis.setObjectName(_fromUtf8("Interlis"))
        Interlis.resize(406, 345)
        self.gridLayout_2 = QtGui.QGridLayout(Interlis)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tabWidget = QtGui.QTabWidget(Interlis)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.modeltab = QtGui.QWidget()
        self.modeltab.setObjectName(_fromUtf8("modeltab"))
        self.gridLayout_7 = QtGui.QGridLayout(self.modeltab)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.mModelFileLabel = QtGui.QLabel(self.modeltab)
        self.mModelFileLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mModelFileLabel.setObjectName(_fromUtf8("mModelFileLabel"))
        self.gridLayout_7.addWidget(self.mModelFileLabel, 1, 0, 1, 1)
        self.mModelLineEdit = QtGui.QLineEdit(self.modeltab)
        self.mModelLineEdit.setObjectName(_fromUtf8("mModelLineEdit"))
        self.gridLayout_7.addWidget(self.mModelLineEdit, 1, 1, 1, 3)
        self.mModelFileButton = QtGui.QPushButton(self.modeltab)
        self.mModelFileButton.setObjectName(_fromUtf8("mModelFileButton"))
        self.gridLayout_7.addWidget(self.mModelFileButton, 1, 4, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem, 2, 0, 1, 1)
        self.mCreateSchemaButton = QtGui.QPushButton(self.modeltab)
        self.mCreateSchemaButton.setEnabled(False)
        self.mCreateSchemaButton.setObjectName(_fromUtf8("mCreateSchemaButton"))
        self.gridLayout_7.addWidget(self.mCreateSchemaButton, 4, 0, 1, 2)
        self.mImportEnumsButton = QtGui.QPushButton(self.modeltab)
        self.mImportEnumsButton.setEnabled(False)
        self.mImportEnumsButton.setObjectName(_fromUtf8("mImportEnumsButton"))
        self.gridLayout_7.addWidget(self.mImportEnumsButton, 4, 2, 1, 2)
        self.mIliGroupBox = gui.QgsCollapsibleGroupBoxBasic(self.modeltab)
        self.mIliGroupBox.setProperty("collapsed", True)
        self.mIliGroupBox.setObjectName(_fromUtf8("mIliGroupBox"))
        self.gridLayout_6 = QtGui.QGridLayout(self.mIliGroupBox)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.mIliLineEdit = QtGui.QLineEdit(self.mIliGroupBox)
        self.mIliLineEdit.setObjectName(_fromUtf8("mIliLineEdit"))
        self.gridLayout_6.addWidget(self.mIliLineEdit, 0, 0, 1, 1)
        self.mCreateIlisMetaButton = QtGui.QPushButton(self.mIliGroupBox)
        self.mCreateIlisMetaButton.setEnabled(False)
        self.mCreateIlisMetaButton.setObjectName(_fromUtf8("mCreateIlisMetaButton"))
        self.gridLayout_6.addWidget(self.mCreateIlisMetaButton, 1, 0, 1, 1)
        self.mIliButton = QtGui.QPushButton(self.mIliGroupBox)
        self.mIliButton.setObjectName(_fromUtf8("mIliButton"))
        self.gridLayout_6.addWidget(self.mIliButton, 0, 2, 1, 1)
        self.gridLayout_7.addWidget(self.mIliGroupBox, 0, 0, 1, 5)
        self.tabWidget.addTab(self.modeltab, _fromUtf8(""))
        self.transfertab = QtGui.QWidget()
        self.transfertab.setObjectName(_fromUtf8("transfertab"))
        self.gridLayout = QtGui.QGridLayout(self.transfertab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cbDbConnections = QtGui.QComboBox(self.transfertab)
        self.cbDbConnections.setObjectName(_fromUtf8("cbDbConnections"))
        self.cbDbConnections.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cbDbConnections, 4, 1, 1, 1, QtCore.Qt.AlignVCenter)
        self.label = QtGui.QLabel(self.transfertab)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.mDataFileButton = QtGui.QPushButton(self.transfertab)
        self.mDataFileButton.setObjectName(_fromUtf8("mDataFileButton"))
        self.gridLayout.addWidget(self.mDataFileButton, 0, 2, 1, 1)
        self.mDataFileLabel = QtGui.QLabel(self.transfertab)
        self.mDataFileLabel.setObjectName(_fromUtf8("mDataFileLabel"))
        self.gridLayout.addWidget(self.mDataFileLabel, 0, 0, 1, 1)
        self.mDataLineEdit = QtGui.QLineEdit(self.transfertab)
        self.mDataLineEdit.setObjectName(_fromUtf8("mDataLineEdit"))
        self.gridLayout.addWidget(self.mDataLineEdit, 0, 1, 1, 1)
        self.frame = QtGui.QFrame(self.transfertab)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 2, 0, 1, 1)
        self.mImportButton = QtGui.QPushButton(self.frame)
        self.mImportButton.setEnabled(False)
        self.mImportButton.setObjectName(_fromUtf8("mImportButton"))
        self.gridLayout_3.addWidget(self.mImportButton, 4, 0, 2, 1)
        self.cbResetData = QtGui.QCheckBox(self.frame)
        self.cbResetData.setChecked(True)
        self.cbResetData.setObjectName(_fromUtf8("cbResetData"))
        self.gridLayout_3.addWidget(self.cbResetData, 3, 0, 1, 1)
        self.mExportButton = QtGui.QPushButton(self.frame)
        self.mExportButton.setEnabled(False)
        self.mExportButton.setObjectName(_fromUtf8("mExportButton"))
        self.gridLayout_3.addWidget(self.mExportButton, 4, 1, 2, 1)
        self.mCfgGroupBox = gui.QgsCollapsibleGroupBoxBasic(self.frame)
        self.mCfgGroupBox.setProperty("collapsed", True)
        self.mCfgGroupBox.setObjectName(_fromUtf8("mCfgGroupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.mCfgGroupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.mConfigLineEdit = QtGui.QLineEdit(self.mCfgGroupBox)
        self.mConfigLineEdit.setObjectName(_fromUtf8("mConfigLineEdit"))
        self.gridLayout_4.addWidget(self.mConfigLineEdit, 0, 0, 1, 1)
        self.mConfigButton = QtGui.QPushButton(self.mCfgGroupBox)
        self.mConfigButton.setObjectName(_fromUtf8("mConfigButton"))
        self.gridLayout_4.addWidget(self.mConfigButton, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.mCfgGroupBox, 1, 0, 1, 3)
        self.gridLayout.addWidget(self.frame, 7, 0, 1, 3)
        self.mModelLookupButton = QtGui.QPushButton(self.transfertab)
        self.mModelLookupButton.setEnabled(False)
        self.mModelLookupButton.setObjectName(_fromUtf8("mModelLookupButton"))
        self.gridLayout.addWidget(self.mModelLookupButton, 3, 1, 1, 1)
        self.tabWidget.addTab(self.transfertab, _fromUtf8(""))
        self.settingstab = QtGui.QWidget()
        self.settingstab.setObjectName(_fromUtf8("settingstab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.settingstab)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.frame_2 = QtGui.QFrame(self.settingstab)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_8 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_5 = QtGui.QLabel(self.frame_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_8.addWidget(self.label_5, 0, 0, 1, 1)
        self.mIli2cLineEdit = QtGui.QLineEdit(self.frame_2)
        self.mIli2cLineEdit.setObjectName(_fromUtf8("mIli2cLineEdit"))
        self.gridLayout_8.addWidget(self.mIli2cLineEdit, 0, 1, 1, 1)
        self.mIlisMetaUrlLineEdit = QtGui.QLineEdit(self.frame_2)
        self.mIlisMetaUrlLineEdit.setEnabled(False)
        self.mIlisMetaUrlLineEdit.setObjectName(_fromUtf8("mIlisMetaUrlLineEdit"))
        self.gridLayout_8.addWidget(self.mIlisMetaUrlLineEdit, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame_2)
        self.label_4.setEnabled(False)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_8.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setEnabled(False)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_8.addWidget(self.label_3, 1, 0, 1, 1)
        self.cbSkipFailures = QtGui.QCheckBox(self.frame_2)
        self.cbSkipFailures.setChecked(True)
        self.cbSkipFailures.setObjectName(_fromUtf8("cbSkipFailures"))
        self.gridLayout_8.addWidget(self.cbSkipFailures, 3, 1, 1, 1)
        self.mIli2cPathButton = QtGui.QPushButton(self.frame_2)
        self.mIli2cPathButton.setObjectName(_fromUtf8("mIli2cPathButton"))
        self.gridLayout_8.addWidget(self.mIli2cPathButton, 0, 2, 1, 1)
        self.mRepoUrlLineEdit = QtGui.QLineEdit(self.frame_2)
        self.mRepoUrlLineEdit.setEnabled(False)
        self.mRepoUrlLineEdit.setObjectName(_fromUtf8("mRepoUrlLineEdit"))
        self.gridLayout_8.addWidget(self.mRepoUrlLineEdit, 1, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem2, 4, 1, 1, 1)
        self.gridLayout_5.addWidget(self.frame_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.settingstab, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Interlis)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.mModelFileLabel.setBuddy(self.mModelLineEdit)
        self.label.setBuddy(self.cbDbConnections)
        self.mDataFileLabel.setBuddy(self.mDataLineEdit)
        self.label_5.setBuddy(self.mIli2cLineEdit)
        self.label_4.setBuddy(self.mIlisMetaUrlLineEdit)
        self.label_3.setBuddy(self.mRepoUrlLineEdit)

        self.retranslateUi(Interlis)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Interlis.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Interlis.reject)
        QtCore.QMetaObject.connectSlotsByName(Interlis)
        Interlis.setTabOrder(self.mDataFileButton, self.mImportButton)
        Interlis.setTabOrder(self.mImportButton, self.mExportButton)
        Interlis.setTabOrder(self.mExportButton, self.cbDbConnections)
        Interlis.setTabOrder(self.cbDbConnections, self.mDataLineEdit)

    def retranslateUi(self, Interlis):
        Interlis.setWindowTitle(_translate("Interlis", "Interlis", None))
        self.mModelFileLabel.setText(_translate("Interlis", "IlisMeta Modell:", None))
        self.mModelFileButton.setText(_translate("Interlis", "...", None))
        self.mCreateSchemaButton.setText(_translate("Interlis", "DB-Tabellen anlegen", None))
        self.mImportEnumsButton.setText(_translate("Interlis", "Enums importieren", None))
        self.mIliGroupBox.setTitle(_translate("Interlis", "Ili Modell", None))
        self.mCreateIlisMetaButton.setText(_translate("Interlis", "IlisMeta erzeugen", None))
        self.mIliButton.setText(_translate("Interlis", "...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.modeltab), _translate("Interlis", "Modell", None))
        self.cbDbConnections.setItemText(0, _translate("Interlis", "QGIS Layers", None))
        self.label.setText(_translate("Interlis", "Speicherort:", None))
        self.mDataFileButton.setText(_translate("Interlis", "...", None))
        self.mDataFileLabel.setText(_translate("Interlis", "Transferfile:", None))
        self.mImportButton.setText(_translate("Interlis", "Import", None))
        self.cbResetData.setText(_translate("Interlis", "Daten ersetzen", None))
        self.mExportButton.setText(_translate("Interlis", "Export", None))
        self.mCfgGroupBox.setTitle(_translate("Interlis", "OGR Config (mapping)", None))
        self.mConfigButton.setText(_translate("Interlis", "...", None))
        self.mModelLookupButton.setText(_translate("Interlis", "Modell Lookup", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.transfertab), _translate("Interlis", "Import/Export", None))
        self.label_5.setText(_translate("Interlis", "ili2c.jar Pfad:", None))
        self.mIlisMetaUrlLineEdit.setText(_translate("Interlis", "http://interlis.sourcepole.ch/wps", None))
        self.label_4.setText(_translate("Interlis", "IlisMeta Lookup:", None))
        self.label_3.setText(_translate("Interlis", "Model Repositories:", None))
        self.cbSkipFailures.setText(_translate("Interlis", "Import-Fehler überspringen", None))
        self.mIli2cPathButton.setText(_translate("Interlis", "...", None))
        self.mRepoUrlLineEdit.setText(_translate("Interlis", "http://models.interlis.ch/", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settingstab), _translate("Interlis", "Einstellungen", None))

from qgis import gui
